/* board_pins.h - GENERATED by /fwe pinmap.py from PCB-0026-A_gan-boost-48v/kicad/PCB-0026-A_gan-boost-48v.net.
 * Do not edit: regenerate with pinmap.py --workspace <board>; the build runs pinmap.py --check.
 * netlist sha256 e70d3f4ec7e290d82d574823038a5144d26e5793948b1260e5155b5bf68a289e */
#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#define BOARD_ID "PCB-0026-A"
#define BOARD_MCU "STM32G474CBT6"

/* PG10 (pin 7) reset */
#define PIN_NRST_PORT GPIOG
#define PIN_NRST_PIN 10u

/* PA0 (pin 8) v_out */
#define PIN_VOUT_SNS_PORT GPIOA
#define PIN_VOUT_SNS_PIN 0u
#define PIN_VOUT_SNS_ADC 1u
#define PIN_VOUT_SNS_ADC_CH 1u /* ADC12_IN1 */
#define PIN_VOUT_SNS_COMP 3u /* COMP3_INP */

/* PA1 (pin 9) i_sense */
#define PIN_ISNS_PORT GPIOA
#define PIN_ISNS_PIN 1u
#define PIN_ISNS_ADC 1u
#define PIN_ISNS_ADC_CH 2u /* ADC12_IN2 */
#define PIN_ISNS_COMP 1u /* COMP1_INP */

/* PA2 (pin 10) uart_tx */
#define PIN_UART_TX_PORT GPIOA
#define PIN_UART_TX_PIN 2u
#define PIN_UART_TX_AF 7u /* USART2_TX */

/* PA3 (pin 11) uart_rx */
#define PIN_UART_RX_PORT GPIOA
#define PIN_UART_RX_PIN 3u
#define PIN_UART_RX_AF 7u /* USART2_RX */

/* PB0 (pin 16) v_in */
#define PIN_VIN_SNS_PORT GPIOB
#define PIN_VIN_SNS_PIN 0u
#define PIN_VIN_SNS_ADC 1u
#define PIN_VIN_SNS_ADC_CH 15u /* ADC1_IN15 */
#define PIN_VIN_SNS_COMP 4u /* COMP4_INP */

/* PB1 (pin 17) ntc */
#define PIN_NTC_SNS_PORT GPIOB
#define PIN_NTC_SNS_PIN 1u
#define PIN_NTC_SNS_ADC 1u
#define PIN_NTC_SNS_ADC_CH 12u /* ADC1_IN12 */

/* PA8 (pin 30) hrtim_lo */
#define PIN_PWM_LO_PORT GPIOA
#define PIN_PWM_LO_PIN 8u
#define PIN_PWM_LO_AF 13u /* HRTIM1_CHA1 */
#define PIN_PWM_LO_HRTIM_TIMER 0u /* HRTIM1_TIMA */
#define PIN_PWM_LO_HRTIM_OUT 1u

/* PA9 (pin 31) hrtim_hi */
#define PIN_PWM_HI_PORT GPIOA
#define PIN_PWM_HI_PIN 9u
#define PIN_PWM_HI_AF 13u /* HRTIM1_CHA2 */
#define PIN_PWM_HI_HRTIM_TIMER 0u /* HRTIM1_TIMA */
#define PIN_PWM_HI_HRTIM_OUT 2u

/* PA13 (pin 37) swd */
#define PIN_SWDIO_PORT GPIOA
#define PIN_SWDIO_PIN 13u

/* PA14 (pin 38) swd */
#define PIN_SWCLK_PORT GPIOA
#define PIN_SWCLK_PIN 14u

/* PB3 (pin 40) swo */
#define PIN_SWO_PORT GPIOB
#define PIN_SWO_PIN 3u
#define PIN_SWO_AF 0u /* SWO */

/* PB6 (pin 43) fan_pwm */
#define PIN_FAN_PWM_PORT GPIOB
#define PIN_FAN_PWM_PIN 6u
#define PIN_FAN_PWM_AF 2u /* TIM4_CH1 */

/* PB8 (pin 45) boot */
#define PIN_BOOT0_PORT GPIOB
#define PIN_BOOT0_PIN 8u

/* unused: PC13 PC14 PC15 PF0 PF1 PA4 PA5 PA6 PA7 PB2 PB10 PB11 PB12 PB13 PB14 PB15 PA10 PA11 PA12 PA15 PB4 PB5 PB7 PB9 */
#define RAIL__3V3_V 3.3f
#define RAIL_VDDA_V 3.3f

#define VOUT_SNS_RATIO 21.0f /* +48V: 200000/10000 ohm */
#define ISNS_GAIN 50.0f /* U301 INA240A2 */
#define ISNS_REF_V 1.65f
#define ISNS_SHUNT_OHM 0.001f /* R101 */
#define VIN_SNS_RATIO 11.0f /* VIN: 100000/10000 ohm */
#define NTC_SNS_PULLUP_OHM 10000.0f /* R308 to +3V3 */
#define NTC_SNS_R25_OHM 10000.0f /* RT201 10k NTC B3380 */
#define NTC_SNS_BETA 3380.0f

/* ovp: VOUT_SNS -> COMP3 -> HRTIM FLT5 */
#define TRIP_OVP_COMP 3u
#define TRIP_OVP_FLT 5u /* RM0440 Rev 9, section 28.3.2 Table 228 (Fault inputs, p.888) and section 11.3.9 Table 84 (Interconnect 11, p.395), FLTxSRC[1:0]=01 */

/* ocp: ISNS -> COMP1 -> HRTIM FLT4 */
#define TRIP_OCP_COMP 1u
#define TRIP_OCP_FLT 4u /* RM0440 Rev 9, section 28.3.2 Table 228 (Fault inputs, p.888) and section 11.3.9 Table 84 (Interconnect 11, p.395), FLTxSRC[1:0]=01 */

#endif /* BOARD_PINS_H */
